services:
  - type: web
    name: books-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: https://github.com/surajw141/Guternberg-API/blob/main/gutendex.sql